def help():
    print(f"\nOption 1: Create New Transaction Record 💵")
    print("This function lets you enter income or expense transactions")
    print(f"\nOption 2: Create New Asset Record 💰")
    print("This function lets you enter details about currently non-spendable assets, like fixed deposits, and any other investment")
    print(f"\nOption 3: Update Value of Existing Asset 💹")
    print("This function lets you update the asset values, without manually changing database entries.")
    print("You can select the ID of the relevant asset, and update the value of it.")
    print("This will be useful for updating volatile assets.")
    print(f"\nOption 4: View Historical Data 🕒")
    print("There are 3 sub options within this function: view summary, view raw data and view both.")
    print("Using the view summary option, you can view an income and expenses breakdown, for a selected month.")
    print("Using the view raw data option, you can view a table of all transactions, for a selected month.")
    print("At the end of view raw data function, you can export the raw data as a .csv file, if preferred.")
    print("Using the both option, both the summary and raw data will be presented, with the option to export as .csv.")
    print(f"\nOption 5: View Financial Status 🗽")
    print("This function will present a concise summary of your current financial status")
    print("It will include your net asset value, along with the spendable balance and a breakdown of assets")
    print(f"\nImportant!: Do not delete storage.db or assets.db files created by the program, as they contain all transaction and asset records.")
